# Generated by Django 4.2.8 on 2023-12-24 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_rental_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalcategory',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Rental Categories'},
        ),
        migrations.AddField(
            model_name='rental',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
