# Generated by Django 4.2.8 on 2023-12-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_rental_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='yearly', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lease_term',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
