# Generated by Django 4.2.8 on 2023-12-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_rental_lease_type_alter_rental_lease_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('years', 'years'), ('months', 'months')], default='years', max_length=128, null=True),
        ),
    ]
